title: test
uuid: 641df046-0e28-4b94-b0e2-1d63ac4875d6
description: Test catalog

catalog:
  
  - ES Crawler:
    category: UF Crawler
    path: ESC/core
    fields: 
      - a:
        type: string
        max_length: 30
      - b:
        type: int
    
  - SP Crawler:
    category: UF Crawler
    path: SPC/core
    fields: 
      - a:
        type: string
        max_length: 30
      - b:
        type: int
    
  - RJ Crawler:
    category: UF Crawler
    path: RJC/core
    fields: 
      - a:
        type: string
        max_length: 30
      - b:
        type: int
